import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `opennextjs-cloudflare build` — bundled third-party
    // output, not our source, and it trips no-require-imports.
    ".open-next/**",
    // Cloudflare binding types, regenerated by `wrangler types`.
    "cloudflare-env.d.ts",
  ]),
]);

export default eslintConfig;
